services:
  # Django Backend API
  - type: web
    name: securecipher-banking-api
    env: python
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn bankingapi.wsgi:application
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://securecipher-banking.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: securecipher-banking-db
          property: connectionString
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SECURE_HSTS_SECONDS
        value: 31536000
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: true
      - key: SECURE_HSTS_PRELOAD
        value: true
      - key: TIME_ZONE
        value: "Africa/Lagos"
      - key: LOG_LEVEL
        value: "INFO"
      - key: TRANSACTION_DAILY_LIMIT
        value: "50000.00"
      - key: MINIMUM_BALANCE
        value: "100.00"
      - key: DEMO_ACCOUNT_BALANCE
        value: "50000.00"
      - key: DEFAULT_CURRENCY
        value: "NGN"
      - key: STATIC_ROOT
        value: "/opt/render/project/src/staticfiles"
      - key: MEDIA_ROOT
        value: "/opt/render/project/src/media"
    healthCheckPath: "/api/health/"
    plan: starter

  # PostgreSQL Database
databases:
  - name: securecipher-banking-db
    databaseName: securecipher_banking
    user: securecipher_user
    plan: starter
